FROM python:3

ENV PYTHONUNBUFFERED=1

WORKDIR /code

COPY requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /code/

# (Optional) You can specify the default command here if you want:
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
