version: "3"

services:
  web:
    build: .
    restart: always
    ports:
      - "80:8000"        # must be an array (use a dash)
    command: python manage.py runserver 0.0.0.0:8000   # 'command' not 'commands'
    volumes:
      - .:/code
      - ./media/:/code/media/
